dist: bionic

addons:
  apt:
    packages:
    - python3-venv
    - python3-pip

script:
  - mv ~/Dmitrii-I/sportmonks ~/sportmonks
  - bash setup-venv.sh
  - bash run-unit-tests.sh
  - bash run-integration-tests.sh
  - bash run-static-code-checks.sh
