dist: bionic

addons:
  apt:
    packages:
    - python3-venv
    - python3-pip

script:
  - cd ~
  - mv "$TRAVIS_BUILD_DIR" ~/sportmonks
  - bash ~/sportmonks/setup-venv.sh
  - bash ~/sportmonks/run-unit-tests.sh
  - bash ~/sportmonks/run-integration-tests.sh
  - bash ~/sportmonks/run-static-code-checks.sh
