name: tests

on: [push]

jobs:
  tests-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:

    - name: checkout repository
      uses: actions/checkout@master

    - name: create symlink
      run: ln -s $(pwd) ~/sportmonks

    - name: install APT packages
      run: |
        sudo apt-get install python3-venv
        sudo apt-get install python3-pip

    - name: setup virtual environment
      run: bash setup-venv.sh

    - name: run static code checks
      run: bash ~/sportmonks/run-static-code-checks.sh

    - name: run unit tests
      run: bash ~/sportmonks/run-unit-tests.sh

    - name: run integration tests
      env:
        SPORTMONKS_API_KEY: ${{ secrets.SPORTMONKS_API_KEY }}
      run: bash ~/sportmonks/run-integration-tests.sh

  tests-windows-2019:
    runs-on: windows-2019
    steps:
      - name: checkout repository
        uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.6'
          architecture: 'x64'

      - name: create symlink
        shell: bash
        run: ln -s $(pwd) ~/sportmonks

      - name: setup virtual environment
        shell: bash
        run: ~/sportmonks/setup-venv.sh

      - name: run static code checks
        shell: bash
        run: ~/sportmonks/run-static-code-checks.sh

      - name: run unit tests
        shell: bash
        run: ~/sportmonks/run-unit-tests.sh

      - name: run integration tests
        env:
          SPORTMONKS_API_KEY: ${{ secrets.SPORTMONKS_API_KEY }}
        shell: bash
        run: ~/sportmonks/run-integration-tests.sh
